version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    networks:
      - backend
      
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    command: gunicorn --bind 0.0.0.0:3050 app:app
    volumes:
      - ./backend/:/app
      - appdata:/var/www/
    environment:
      - DB_HOST=mongo
      - DB=test
    networks:
      - backend  
    depends_on:
      - mongo
    ports:
      - "5000:3050"   

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017" 
    networks:
      - backend

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    networks:
      - backend

networks: 
  backend:
    driver: bridge

volumes:
    data:
      driver: local
    appdata:
      driver: local